name: LSIF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components:  rust-analyzer-preview, rust-src
      - run: mkdir lsif_index
      - name: Generate LSIF
        run: rustup run nightly rust-analyzer lsif .\Cargo.toml > lsif_index/index.lsif
      - name: Upload LSIF as Action Artifact
        uses: actions/upload-artifact@v3
        with:
          name: index.lsif
          path: lsif_index/index.lsif
      

